import antfu from '@antfu/eslint-config'

export default antfu(
  {
		type: "app",
    react: true,
		typescript: true,
		formatters: true,
		stylistic: {
			indent: 2,
			semi: true,
			quotes: "double",
		},
		ignores: [
			"**/migrations/*",
			"*.config.***",
			"**/dist/**",
			"**/node_modules/**",
			"**/.nuxt/**",
			"**/.output/**",
			"**/coverage/**",
			"**/public/**",
			"**/build/**",
			// Throwaway design sketches: standalone HTML mockups kept as a record
			// of what was explored, not code we ship or maintain. Linting them
			// accounted for 757 of the 885 problems this config used to report.
			".planning/**",
			// Generated by @tanstack/router-plugin; regenerated on every build.
			"src/routeTree.gen.ts",
			// Tooling state, not source.
			"conductor/**",
			// Prose docs. The fenced snippets in these are illustrative fragments,
			// not compilable modules, so parsing them as TypeScript only produces
			// noise.
			"*.md",
		],
	},
	{
		rules: {
		"ts/no-redeclare": "off",
    "no-console": ["warn"],
    "antfu/no-top-level-await": ["off"],
    "node/prefer-global/process": ["off"],
    "node/no-process-env": ["error"],
			"perfectionist/sort-imports": ["error", {
      tsconfigRootDir: ".",
    }],
			"unicorn/filename-case": [
				"error",
				{
					case: "kebabCase",
					// Root documentation files are conventionally SCREAMING_CASE and
					// are looked up by that exact name by tooling and by humans;
					// renaming AGENTS.md to agents.md would break the convention it
					// exists to advertise.
					ignore: [
						"README\\.md",
						"AGENTS\\.md",
						"DESIGN\\.md",
						"PRODUCT\\.md",
						"GEMINI\\.md",
						"CLAUDE\\.md",
						"App\\.tsx",
						".*\\.test\\.tsx$",
					],
				},
			],
		},
	},
)
