/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'

const ServicesLazyRouteImport = createFileRoute('/services')()
const ContactLazyRouteImport = createFileRoute('/contact')()
const BlogLazyRouteImport = createFileRoute('/blog')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const ProjectsSlugLazyRouteImport = createFileRoute('/projects/$slug')()

const ServicesLazyRoute = ServicesLazyRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/services.lazy').then((d) => d.Route))
const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const BlogLazyRoute = BlogLazyRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProjectsSlugLazyRoute = ProjectsSlugLazyRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any).lazy(() =>
  import('./routes/projects.$slug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/services': typeof ServicesLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/services': typeof ServicesLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/blog': typeof BlogLazyRoute
  '/contact': typeof ContactLazyRoute
  '/services': typeof ServicesLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/about'
    | '/blog'
    | '/contact'
    | '/services'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  BlogLazyRoute: typeof BlogLazyRoute
  ContactLazyRoute: typeof ContactLazyRoute
  ServicesLazyRoute: typeof ServicesLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugLazyRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugLazyRoute: typeof ProjectsSlugLazyRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugLazyRoute: ProjectsSlugLazyRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  BlogLazyRoute: BlogLazyRoute,
  ContactLazyRoute: ContactLazyRoute,
  ServicesLazyRoute: ServicesLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
